version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy
permissions:
  - object: /home/ec2-user/deploy
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ec2-user
