version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy

permissions:
  - object: /home/ec2-user/deploy
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: start.sh
      timeout: 300
      runas: ec2-user
