version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo yum update -y
      - sudo yum install -y gcc-c++ make
      - sudo yum install -y nodejs
      - npm install -g pm2

  build:
    commands:
      - echo "Installing application dependencies..."
      - npm install # Runs in the CodeBuild environment, not on EC2

  post_build:
    commands:
      - echo "Build completed."
artifacts:
  files:
    - '**/*'
