version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Fixing npm permissions..."
      - npm config set unsafe-perm true
      - npm config get registry
      - curl -I https://registry.npmjs.org
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - npm install --verbose
timeout-in-minutes: 10
  post_build:
    commands:
      - echo "Build complete. Preparing for deployment..."

artifacts:
  files:
    - '**/*'
  base-directory: .
