version: 0.2

phases:
  install:
    commands:
      - echo "Skipping Node.js installation in CodeBuild. It will be installed on EC2."
      - sudo yum update -y
      - sudo yum install -y gcc-c++ make

  build:
    commands:
      - echo "Installing application dependencies..."
      - npm install # Runs in the CodeBuild environment, not on EC2

  post_build:
    commands:
      - echo "Build completed."
artifacts:
  files:
    - '**/*'
