version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
  post_build:
    commands:
      - echo "Build complete. Preparing for deployment..."

artifacts:
  files:
    - '**/*'
  base-directory: .
