apiVersion: v1
kind: Service
metadata:
  name: simple-node-app-service
spec:
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 80      # External port
      targetPort: 3000  # The port your app is listening on inside the container
  type: NodePort
